nguage: objective-c
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool test -xcproject BCPay.xcproject -scheme BCPayTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
